### PR TITLE
Adds lorem faker

### PR DESCRIPTION
**Pull request by georgepapas**
Adds a lorem faker which provides words and sentences.

### CODE REVIEW

**Review by drager — COMMENTED** [review]
Thank you so much for this @georgepapas! I think the code looks good. I would appreciate if you could add documentation comments for all the functions. See an example of that here: https://github.com/drager/faker/blob/master/lib/src/food.dart

**Comment by georgepapas** [comment]
Thanks @drager , I've added the API docs as requested.

Cheers
George

**Review by drager — APPROVED** [review]

**Comment by drager** [comment]
Thanks a lot @georgepapas!

**Comment by georgepapas** [comment]
Hey no problem @drager , would be awesome to get a release to pub ;)

**Comment by drager** [comment]
@georgepapas: Yes, I will publish to pub soon :blush:

**Comment by georgepapas** [comment]
> @georgepapas: Yes, I will publish to pub soon

bump ;)

**Comment by drager** [comment]
@georgepapas Sorry that it took so long. Now it's published: https://pub.dev/packages/faker/versions/1.1.0

**Comment by georgepapas** [comment]
thanks @drager !

**Pull request merged**
