### PR TITLE
Nnbd

### PR DESCRIPTION
**Pull request by mnordine**

### CODE REVIEW

**Comment by drager** [comment]
@mnordine Thanks for the PR but I just merged #38 that addresses this

**Comment by mnordine** [comment]
Actually, I wish you took a closer look at the pull requests, I think there are some mistakes and some properties that are nullable for no reason in the other one.

**Comment by drager** [comment]
> Actually, I wish you took a closer look at the pull requests, I think there are some mistakes and some properties that are nullable for no reason in the other one.

Alright! Feel free to merge master into your branch and correct the mistakes if you want to.

**Comment by DanMossa** [comment]
When I currently
`flutter pub upgrade --null-safety --dry-run`
This package shows up under not having a null-safety compatible version.
Will this PR fix that?

Thanks!

**Comment by drager** [comment]
@DanMossa Please try out [2.0.0-rc-1](https://pub.dev/packages/faker/versions/2.0.0-rc.1)

**Pull request closed without merging**
