### PR TITLE
adding FakerDataProvider

### PR DESCRIPTION
**Pull request by easazade**
Connected to #30 

hey @drager 
I made a few changes. just adding the feature of accepting a `FakerDataProvider` to the Faker class.
right now `FakerDataProvider` only accepts a `LoremDataProvider`.

also added a `FakerDataProviderFa` which does provide farsi lorem text.
review the code if it looks ok let me know to do the same job with the other parts like address, person, etc.

### CODE REVIEW

**Comment by easazade** [comment]
Did you get a chance to look at it?

**Comment by drager** [comment]
> Did you get a chance to look at it?

Just looked at it. Thanks! Will make sure the build passes before merging.

**Review by drager — APPROVED** [review]

**Comment by easazade** [comment]
have you published it? because I don't get the last version when I include it in `pubspec.yaml` dependencies

**Comment by drager** [comment]
@easazade I have not published it just yet

**Comment by drager** [comment]
@easazade Published in [2.0.0-rc-1](https://pub.dev/packages/faker/versions/2.0.0-rc.1)

**Pull request merged**
