### PR TITLE
-Swap out unittest and guiness packages for package:test, set env to Dart 2.0

### PR DESCRIPTION
**Pull request by SimplyFaisal**
Hi thanks for taking the time to develop this faker implementation. I'm currently working on an app in flutter and i was using it to fake data in some models. 

I just upgraded my flutter install and sadly it isn't compatible with my current version of flutter. I can't remember my exact errors but the main issue was with the testing dependencies(unittest and guinness). Thankfully a lot of what they provided is available in package:test so I was able to easily port the tests over and remove any dependencies. I also set the environment to Dart 2.0.

### CODE REVIEW

**Comment by drager** [comment]
Hi! Thank you for submitting this PR. I will go through this and test it out in the nearest days.

**Review by drager — APPROVED** [review]
Thank you for taking the time to do these changes. I have tested it and all the tests pass on the 2.0.0 dart SDK. I will merge this and publish a new version at pub.

**Comment by drager** [comment]
@SimplyFaisal: faker version 1.0.0 is now published to pub: https://pub.dartlang.org/packages/faker

**Comment by SimplyFaisal** [comment]
Thank you Jesper!

**Pull request merged**
